embeddings {
  tensor_name: "embedding_4:0"
  metadata_path: "E:/TensorflowCode/Jupyter/TensorflowLearningAndApplication/projector/projector/metadata.tsv"
  sprite {
    image_path: "E:/TensorflowCode/Jupyter/TensorflowLearningAndApplication/projector/data/mnist_10k_sprite.png"
    single_image_dim: 28
    single_image_dim: 28
  }
}
